name: Deploy Restaurant Service

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/restaurant-service/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd backend/restaurant-service
        mvn clean package -DskipTests

    - name: Run Tests
      run: |
        cd backend/restaurant-service
        mvn test

    - name: Build Docker image
      run: |
        cd backend/restaurant-service
        docker build -t quisin/restaurant-service:${{ github.sha }} .
        docker tag quisin/restaurant-service:${{ github.sha }} quisin/restaurant-service:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push quisin/restaurant-service:${{ github.sha }}
        docker push quisin/restaurant-service:latest

    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd /opt/quisin
          docker-compose pull restaurant-service
          docker-compose up -d restaurant-service
          docker system prune -f 