spring:
  application:
    name: reservation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/quisin_reservation_db
    username: ${RESERVATION_DB_USER}
    password: ${RESERVATION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reservation-service
      auto-offset-reset: earliest

server:
  port: 8090
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.quisin.reservation: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

reservation:
  max-per-slot: 10
  min-notice-minutes: 30
  max-advance-days: 30
  slot-duration-minutes: 30
  operating-hours:
    start: "10:00"
    end: "22:00"
