package com.quisin.document.model;

public enum DocumentType {
    QR_CODE,
    SALES_REPORT,
    INVENTORY_REPORT,
    CUSTOMER_REPORT,
    RESERVATION_REPORT,
    ORDER_REPORT,
    STAFF_REPORT,
    FINANCIAL_REPORT,
    TABLE_REPORT,
    MENU_REPORT,
    PERFORMANCE_REPORT,
    ANALYTICS_REPORT,
    RESTAURANT_CREDENTIALS,
    AUDIT_REPORT
} 