server:
  port: 8089
  servlet:
    context-path: /api/v1/qrcode

spring:
  application:
    name: qrcode-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/quisin_qrcode_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

quisin:
  qrcode:
    base-url: ${QUISIN_BASE_URL:http://localhost:3000}
    brand-color: "#FF6B00"
  services:
    restaurant:
      url: ${RESTAURANT_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name} 