server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/quisin_user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.quisin.user: DEBUG

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]
  health:
    db:
      enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-here-must-be-at-least-256-bits}
    expiration: 86400000  # 24 hours in milliseconds 