server:
  port: 8081

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/quisin_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  redis:
    host: redis
    port: 6379

jwt:
  secret: "dGhpcy1pcy1hLXZlcnktc2VjdXJlLTI1Ni1iaXQtc2VjcmV0LWtleS1mb3ItcXVpc2luLWF1dGgtc2VydmljZQ=="
  expiration: 86400000 # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds

sentry:
  dsn: ${SENTRY_DSN:}
  environment: docker
  traces-sample-rate: 1.0

logging:
  level:
    root: INFO
    com.quisin: DEBUG
    org.springframework.security: INFO 