spring:
  application:
    name: menu-service

  datasource:
    url: jdbc:postgresql://localhost:5432/quisin_db
    username: quisin_user
    password: quisin_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: menu-service-group
    topics:
      menu-updates: menu-updates-topic
      inventory-changes: inventory-changes-topic

server:
  port: 8083
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.quisin.menu: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

quisin:
  services:
    notification:
      url: http://notification-service:8085
  images:
    storage-path: ${QUISIN_IMAGES_PATH:/tmp/quisin/images}
    max-width: 1200
    max-height: 1200
    quality: 0.85

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
