name: Auth Service CI

on:
  push:
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-ci.yml'
  pull_request:
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    
    - name: Build with Maven
      run: |
        cd auth-service
        mvn clean verify
    
    - name: Run Unit Tests
      run: |
        cd auth-service
        mvn test
    
    - name: Build Docker Image
      run: |
        cd auth-service
        docker build -t quisin-auth-service .
    
    - name: Run Security Scan
      uses: anchore/scan-action@v3
      with:
        path: "auth-service"
        fail-build: false
        severity-cutoff: critical
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: auth-service-jar
        path: auth-service/target/*.jar
