spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL}/.well-known/openid-configuration
          jwk-set-uri: ${AUTH_SERVICE_URL}/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: restaurant-service
    enable:
      jvm: true
      process: true
      system: true

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 2048 