spring:
  config:
    import: application-base.yml
  
  datasource:
    url: jdbc:postgresql://localhost:5432/quisin_restaurant_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.quisin.restaurant: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoint:
    health:
      show-details: always 