spring:
  application:
    name: review-service

  datasource:
    url: jdbc:postgresql://localhost:5432/quisin_review_db
    username: ${REVIEW_DB_USER}
    password: ${REVIEW_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: review-service
      auto-offset-reset: earliest

  cloud:
    stream:
      bindings:
        reviewEvents-out-0:
          destination: review-events
          content-type: application/json
      kafka:
        binder:
          brokers: ${spring.kafka.bootstrap-servers}

server:
  port: 8091
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.quisin.review: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: review-service

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

review:
  moderation:
    auto-approve: false
    min-rating: 1
    max-rating: 5
    min-comment-length: 10
    max-comment-length: 1000
    forbidden-words: ${FORBIDDEN_WORDS:}
    max-reviews-per-order: 1
    max-reviews-per-user-per-day: 5 